### ISSUE TITLE
!important is deleted

### ISSUE THREAD

**Issue by novita** [alexandr-solovyov/postcss-responsive-properties#5]
*!important* string is deleted like below.
please fix it!

```
.show_sp {
  @display: {
    default: initial;
    bp_pc: none !important;
  }
}
```

goes

```
.show_sp {
  display: initial;
}

@media screen and (min-width: 960px) {
  .show_sp {
    display: none;
  }
}
```

**Comment by alex-solovev** [comment]
Fixed! Thanks for feedback :)

**Comment by novita** [comment]
Thanks.
But still missing important at **_default_**.

```
.show_sp {
  @display: {
    default: block !important;
    bp_pc: none !important;
  }
}
```

goes

```
.show_sp {
  display: block;
}

@media screen and (min-width: 960px) {
  .show_sp {
    display: none !important;
  }
}
```

**Comment by alex-solovev** [comment]
Hello, sorry for such a late answer.
Few minutes ago I was published new major version of plugin. Now syntax is slightly different: no need to write at-symbol before property name, also I removed dependencies on merge-rules and variables - now it's standalone, and, of course, your issue was fixed :) Check it if this still make sense.
